Final touches
tta2yta/Leaderboard pull request #3
Opened 2021-07-28 22:34 UTC by tta2yta

2021-07-28 23:01 UTC, Dipeshtwis requested changes
Hi @tta2yta, 

:+1: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
:+1: README file looks professional and contains all that's needed for running the app.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


 ## Required Changes ♻️

**_Check the comments under the review_**

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**_Check the comments under the review_**

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**_Dipesh Kumar_**


------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-28 23:01 UTC, Dipeshtwis commented on src/style.css
> +}
- [ ] The submit button is not in the right position and the layout looks little different. Please fix this.

### Your design 

![Screenshot from 2021-07-29 04-19-34](https://user-images.githubusercontent.com/22434660/127406597-dcabc4af-a1d2-4998-bdb4-f4238cc32f3e.png)


### Wireframe design 

![Screenshot from 2021-07-29 04-20-17](https://user-images.githubusercontent.com/22434660/127406588-128fd6c2-643a-47d5-924e-14bfdf772317.png)

2021-07-28 23:01 UTC, Dipeshtwis commented on src/style.css
> +}
[OPTIONAL]

- I would recommend to use whole window as container instead of making a little one which left so much gap in the UI.

2021-07-29 18:19 UTC, bellom approved these changes
## Hi @tta2yta  👏  

**Great work making all the necessary corrections from the previous review.**

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

### Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-29 18:27 UTC, merged